### ISSUE TITLE
Update question

### ISSUE THREAD

**Issue by xww52526** [antigenomics/vdjviz#41]
Hello,

Seems latest commit for vdjviz was Oct,2016. Is there any plan of releasing a new version? 

I tried to install the stand-alone vdjviz on Mac & windows, but there were some java issues:
`[info] play - database [default] connected at jdbc:h2:file:~/vdjviz/h2.db
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at com.avaje.ebeaninternal.server.core.BootupClasses.isXmlBean(BootupClasses.java:425)
	at com.avaje.ebeaninternal.server.core.BootupClasses.isMatch(BootupClasses.java:329)
	at com.avaje.ebeaninternal.server.core.BootupClasses.process(BootupClasses.java:96)
	at com.avaje.ebeaninternal.server.core.BootupClasses.<init>(BootupClasses.java:73)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getBootupClasses1(DefaultServerFactory.java:322)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getBootupClasses(DefaultServerFactory.java:302)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:161)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:52)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:316)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:311)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:311)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 25 more
`
Any idea how to fix this error? Thanks!

**Comment by mikessh** [comment]
Hello,

When we finish with updating VDJdb web server it is likely we'll have enough time to update VDJviz (or completely rewrite it, focusing on some essential analysis options).

As for second part of this question, perhaps @bvdmitri can elaborate

**Comment by bvdmitri** [comment]
@xww52526 
Hello!
Can you tell us more about application environment?
Which java, scala version do you use?
vdjviz application was not tested with latest Java9 version.

**Comment by xww52526** [comment]
Thank you! My java & scala on mac:
`java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
Scala code runner version 2.12.4 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.`

on windows virtual box:
`java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)`

Which Java/scala version you recommend for VDJviz? Thanks!

**Comment by bvdmitri** [comment]
@xww52526 
It should work with 1.7 and 1.8 java version (currently we are using 1.8.0_91 java on our server).
Recommended scala compiler version should be installed automatically while compiling vdjviz application.

Also make sure you are using Play 2.2.4 version (Application was not testet with new versions of framework). It can be downloaded [here](https://www.playframework.com/download#older-versions).

In addition you can download latest release binaries of vdjviz application from [GitHub](https://github.com/antigenomics/vdjviz/releases). Instruction on how to run the release application is described [here](https://github.com/antigenomics/vdjviz#installation).

Tell me if it was useful or you need more help with vdjviz installation.
